export class trans_request {
    constructor(
        public inDocID,
        public sDocRequestNo,
        public nItemType,
        public sItemType,
        public nDocType,
        public sDocType,
        public sDocInternal_External,
        public sDocInternalExternal,
        public sDocName,
        public sDocNo,
        public nParcelType,
        public sParcelType,
        public nDeliveryType,
        public sDeliveryType,
        public nMailtype,
        public sMailtype,
        public nDeliveryPoint,
        public sDeliveryPoint,
        public sNotes,
        public nStep,
        public cStatus,
        public sApproveID,
        public sApprove_Comment,
        public sSendID,
        public sSendName,
        public sSendUnitCode,
        public sSendUnitName,
        public dSend,
        public dReceive,
        public nUsermaker,
        public cDel,
        public sCreateBy,
        public dCreate,
        public sUpdateBy,
        public dUpdate,
        public cSendMail,
        public cRefer,
        public nDocID_parent,
        public sTrackingNumber,
        public sStepName,
        public sStepIcon,
        public sRecipientID,
        public sRecipientName,
        public sSendPlace,
        public sBarCodeID
    ) { }

}